### ISSUE TITLE
Unable to launch ebcl-UI at some time period, as it shows authentication error for artifactory( error 403 and 404)

### ISSUE THREAD

**Issue by anjo273727** [Elektrobit/nautilos-repo-setup#4]
userid: anjo273727
As a part of TATA mvp project, while launching ebcl-ui(without vpn) especially from 11:30 am-4:00 pm Indian time, I am getting the below error while selecting Testing/local.

user22@user22-VirtualBox:~/tata_mvm$ ./ebcl-ui 

dpkg: warning: ignoring request to remove bootstrap-root-ubuntu-jammy which isn't installed

dpkg: warning: ignoring request to remove reference-image-description-crinit which isn't installed

--2023-04-06 12:13:36--  https://artifactory.elektrobit.com/eb_corbos_linux_nautilos2.0-debian-remote/release/xUbuntu_22.04_debbuild/all/

Resolving artifactory.elektrobit.com (artifactory.elektrobit.com)... 213.95.163.237

Connecting to artifactory.elektrobit.com (artifactory.elektrobit.com)|213.95.163.237|:443... connected.

HTTP request sent, awaiting response... 401 

Authentication selected: Basic realm="Artifactory Realm"

Reusing existing connection to artifactory.elektrobit.com:443.

HTTP request sent, awaiting response... 403 

2023-04-06 12:13:38 ERROR 403: (no description).

Could you please help me here @schaefi, Schäfer, Marcus

**Comment by schaefi** [comment]
Handled in #3
