### ISSUE TITLE
Unable to launch ebcl-ui to create EBlinux5 Image

### ISSUE THREAD

**Issue by shgh272710** [Elektrobit/nautilos-repo-setup#5]
username:- shgh272710
Location:-   EB India
As a part of Tata MVP project requirement, have to build Eblinux5 Image using ebcl-ui command but receiving below error logs :-

**When Testing Option is selected in EBCL-UI:-**
shrungar@shrungar-adg:~/workspace$ ebcl-ui
[sudo] password for shrungar:

dpkg: error: cannot access archive '/var/tmp/nautilos/artifactory.elektrobit.com/eb_corbos_linux_nautilos2.0-releases-generic/release/xUbuntu_22.04_debbuild/all/nautilos-repo-setup*': No such file or directory

**when Local Option is selected in **EBCL-UI:-****
shrungar@shrungar-adg:~/workspace$ ebcl-ui

Once ebcl-ui command is issued, UI pop-up with testing and local option and once local option is selected ,no logs comes out from terminal and after few seconds same UI pops-up again .

@schaefi Could you please suggest on the above mentioned Issue. Thanks

**Comment by schaefi** [comment]
Handled in #3
